### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by paramsingh** [CSEC-NITH/csec.nith.ac.in#11]
apache doesn't seem to start.

**Comment by paramsingh** [comment]
@shivamtripathi @ferbncode, take a look if you get the time please.

**Comment by shivamtripathi** [comment]
Hey, @paramsingh I don't think I am working on this. Did you mean to tag somebody else?

**Comment by paramsingh** [comment]
@shivamtripathi, whoops, meant to tag @shivam-tripathi, sorry!

**Comment by shivam-tripathi** [comment]
@paramsingh Up and running now.

**Comment by paramsingh** [comment]
Mind writing out what the problem was? (for the future)

**Comment by shivam-tripathi** [comment]
There was a `Listen 443` in `/etc/httpd/conf.d/ssl.conf` (how did it end up there?). Removing that solved this.
There have been similar issues (quick googlefu shows it), so hopefully nothing to panic(?)

**Comment by paramsingh** [comment]
Thanks, fixed!
